setting:
  seed: 20000812
  os_environ:
    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
    MASTER_ADDR: 127.0.0.1
    MASTER_PORT: 12315
    WORLD_SIZE: 1
    NODE_RANK: 0

  out_path: /content/saprot/output/ProteinGym/esm2_t33_650M_UR50D.tsv
  dataset_dir: LMDB/ProteinGym/substitutions

model:
  model_py_path: saprot/saprot_mutation_model
  kwargs:
    config_path: weights/PLMs/esm2_t33_650M_UR50D
    load_pretrained: True

dataset:
  dataset_py_path: mutation_zeroshot_dataset
  dataloader_kwargs:
    batch_size: 1
    num_workers: 2
  kwargs: {}

Trainer:
  log_every_n_steps: 1
  devices: 1
  accelerator: gpu
  num_nodes: 1
  strategy:
    find_unused_parameters: False
  logger: False
